<?php
require_once __DIR__ . '/../../includes/header.php';
$db=getDB();$id=(int)($_GET['id']??0);$clienteId=(int)($_GET['cliente_id']??0);$proposta=[];$itens=[];
if($id){$st=$db->prepare('SELECT * FROM propostas WHERE id=?');$st->execute([$id]);$proposta=$st->fetch();if(!$proposta){header('Location:index.php');exit;}$st=$db->prepare('SELECT * FROM proposta_itens WHERE proposta_id=? ORDER BY ordem,id');$st->execute([$id]);$itens=$st->fetchAll();}
$clientes=$db->query("SELECT id,tipo_pessoa,nome,razao_social,nome_fantasia,cidade,estado,consumo_medio_kwh,tipo_telhado FROM clientes WHERE ativo=1 ORDER BY nome,razao_social")->fetchAll();
$produtos=$db->query("SELECT id,nome,codigo,unidade,preco_venda FROM produtos WHERE ativo=1 ORDER BY nome")->fetchAll();
$meses=['jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez'];
if($_SERVER['REQUEST_METHOD']==='POST'){
  $d=$_POST;$db->beginTransaction();
  try{
    $ger=[];$con=[];foreach($meses as $m){$ger[]=(float)($d['geracao_'.$m]??0);$con[]=(float)($d['consumo_'.$m]??0);}
    $fields=['cliente_id','status','titulo','data_proposta','validade','localidade','tipo_estrutura','potencia_kwp','quantidade_modulos','geracao_anual_kwh','geracao_mensal_kwh','area_necessaria_m2','grupo_consumidor','modo_dimensionamento','consumo_mensal_kwh','tarifa_energia','inclui_iluminacao','valor_iluminacao','tusd_percentual','simultaneidade_percentual','tipo_conexao','tensao_rede','eficiencia_percentual','hsp','estado','cidade','fornecedor_nome','tipo_dimensionamento','painel_descricao','painel_potencia_wp','inversor_descricao','valor_equipamentos','valor_servicos','desconto','valor_total','entrada','saldo','condicoes_pagamento','itens_inclusos','observacoes'];
    $vals=[];foreach($fields as $f){$vals[$f]=$d[$f]??null;if($vals[$f]==='')$vals[$f]=null;}$vals['geracao_meses']=json_encode($ger);$vals['consumo_meses']=json_encode($con);$vals['usuario_id']=$_SESSION['usuario_id'];
    if($id){$set=implode(', ',array_map(fn($f)=>"$f=:$f",array_keys($vals)));$vals['id']=$id;$db->prepare("UPDATE propostas SET $set WHERE id=:id")->execute($vals);$pid=$id;$db->prepare('DELETE FROM proposta_itens WHERE proposta_id=?')->execute([$pid]);}
    else{$numero='PROP'.date('Ymd').str_pad((int)$db->query('SELECT COUNT(*)+1 FROM propostas')->fetchColumn(),4,'0',STR_PAD_LEFT);$vals['numero']=$numero;$cols=implode(',',array_keys($vals));$ph=implode(',',array_map(fn($f)=>":$f",array_keys($vals)));$db->prepare("INSERT INTO propostas ($cols) VALUES ($ph)")->execute($vals);$pid=(int)$db->lastInsertId();}
    $desc=$d['item_descricao']??[];foreach($desc as $i=>$texto){$texto=trim($texto);if($texto==='')continue;$produto=($d['item_produto'][$i]??'')?:null;$q=(float)($d['item_quantidade'][$i]??1);$u=$d['item_unidade'][$i]??'un';$preco=(float)($d['item_preco'][$i]??0);$total=$q*$preco;$db->prepare('INSERT INTO proposta_itens(proposta_id,produto_id,descricao,quantidade,unidade,preco_unitario,total,ordem) VALUES(?,?,?,?,?,?,?,?)')->execute([$pid,$produto,$texto,$q,$u,$preco,$total,$i]);}
    $db->commit();$_SESSION['msg']=$id?'Proposta atualizada com sucesso!':'Proposta criada com sucesso!';header('Location:view.php?id='.$pid);exit;
  }catch(Throwable $e){$db->rollBack();$erro='Não foi possível salvar: '.$e->getMessage();}
}
$v=$proposta?:$_POST;if(!$id&&$clienteId)$v['cliente_id']=$clienteId;
$ger=json_decode($v['geracao_meses']??'[]',true)?:[];$con=json_decode($v['consumo_meses']??'[]',true)?:[];
if(!$itens)$itens=[['produto_id'=>'','descricao'=>'KIT FOTOVOLTAICO','quantidade'=>1,'unidade'=>'kit','preco_unitario'=>0]];
?>
<div class="page-header"><div class="page-title"><i class="fa-solid fa-file-signature"></i> <?= $id?'Editar proposta':'Nova proposta' ?></div><a href="index.php" class="btn btn-outline"><i class="fa-solid fa-arrow-left"></i> Voltar</a></div>
<?php if(!empty($erro)):?><div class="alert alert-danger"><?= htmlspecialchars($erro) ?></div><?php endif;?>
<form method="POST" id="formProposta">
<div class="proposal-steps" role="tablist"><button type="button" class="active" data-go="1">1 <span>Envolvidos</span></button><button type="button" data-go="2">2 <span>Sistema</span></button><button type="button" data-go="3">3 <span>Irradiação</span></button><button type="button" data-go="4">4 <span>Dimensionamento</span></button><button type="button" data-go="5">5 <span>Outras informações</span></button></div>
<div class="wizard-pane active" data-step="1"><div class="card"><div class="card-header"><span class="card-title">Envolvidos e situação</span></div><div class="card-body"><div class="form-row cols-3"><div class="form-group"><label>Colaborador</label><input value="<?= htmlspecialchars($_SESSION['usuario_nome']??'Usuário responsável') ?>" readonly></div><div class="form-group"><label>Cliente *</label><select name="cliente_id" id="cliente" required><option value="">Selecione</option><?php foreach($clientes as $c):$n=$c['tipo_pessoa']==='fisica'?$c['nome']:($c['nome_fantasia']?:$c['razao_social']);?><option value="<?= $c['id'] ?>" data-nome="<?= htmlspecialchars($n) ?>" data-local="<?= htmlspecialchars(trim(($c['cidade']??'').'/'.($c['estado']??''))) ?>" data-cidade="<?= htmlspecialchars($c['cidade']??'') ?>" data-estado="<?= htmlspecialchars($c['estado']??'') ?>" data-consumo="<?= (float)$c['consumo_medio_kwh'] ?>" data-estrutura="<?= htmlspecialchars($c['tipo_telhado']??'') ?>" <?= ($v['cliente_id']??'')==$c['id']?'selected':'' ?>><?= htmlspecialchars($n) ?></option><?php endforeach;?></select></div><div class="form-group"><label>Status</label><select name="status"><?php foreach(['rascunho'=>'Rascunho','enviada'=>'Enviada','aprovada'=>'Aprovada','recusada'=>'Recusada','vencida'=>'Vencida'] as $k=>$l):?><option value="<?= $k ?>" <?= ($v['status']??'rascunho')===$k?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></div></div><div id="clienteResumo" class="client-summary">Selecione um cliente para carregar localidade e consumo.</div><div class="form-row cols-3"><div class="form-group"><label>Título</label><input name="titulo" value="<?= htmlspecialchars($v['titulo']??'Usina Fotovoltaica') ?>"></div><div class="form-group"><label>Data</label><input type="date" name="data_proposta" value="<?= htmlspecialchars($v['data_proposta']??date('Y-m-d')) ?>" required></div><div class="form-group"><label>Validade</label><input type="date" name="validade" value="<?= htmlspecialchars($v['validade']??date('Y-m-d',strtotime('+7 days'))) ?>"></div></div></div></div></div>
<div class="wizard-pane" data-step="2"><div class="card"><div class="card-header"><span class="card-title">Dados de consumo do sistema</span></div><div class="card-body"><div class="form-row cols-3"><div class="form-group"><label>Grupo consumidor</label><select name="grupo_consumidor"><option <?= ($v['grupo_consumidor']??'Grupo B')==='Grupo B'?'selected':'' ?>>Grupo B</option><option <?= ($v['grupo_consumidor']??'')==='Grupo A'?'selected':'' ?>>Grupo A</option></select></div><div class="form-group"><label>Modo de dimensionamento</label><select name="modo_dimensionamento"><option value="kwh" <?= ($v['modo_dimensionamento']??'kwh')==='kwh'?'selected':'' ?>>Consumo médio (kWh)</option><option value="mes_a_mes" <?= ($v['modo_dimensionamento']??'')==='mes_a_mes'?'selected':'' ?>>Consumo mês a mês</option><option value="kwp" <?= ($v['modo_dimensionamento']??'')==='kwp'?'selected':'' ?>>Potência informada (kWp)</option></select></div><div class="form-group"><label>Consumo médio mensal (kWh)</label><input id="consumoMensal" type="number" step="0.01" name="consumo_mensal_kwh" value="<?= htmlspecialchars($v['consumo_mensal_kwh']??'') ?>"></div></div><div class="form-row cols-4"><div class="form-group"><label>Tarifa de energia (R$/kWh)</label><input type="number" step="0.01" name="tarifa_energia" value="<?= htmlspecialchars($v['tarifa_energia']??'1.20') ?>"></div><div class="form-group"><label>TUSD Fio B (%)</label><input type="number" step="0.01" name="tusd_percentual" value="<?= htmlspecialchars($v['tusd_percentual']??'41.51') ?>"></div><div class="form-group"><label>Simultaneidade (%)</label><input type="number" step="0.01" name="simultaneidade_percentual" value="<?= htmlspecialchars($v['simultaneidade_percentual']??'30') ?>"></div><div class="form-group"><label>Eficiência do sistema (%)</label><input id="eficiencia" type="number" min="1" max="100" step="0.1" name="eficiencia_percentual" value="<?= htmlspecialchars($v['eficiencia_percentual']??'80') ?>"></div></div><div class="form-row cols-4"><div class="form-group"><label>Tipo de conexão</label><select name="tipo_conexao"><?php foreach(['Monofásico','Bifásico','Trifásico'] as $x):?><option <?= ($v['tipo_conexao']??'Monofásico')===$x?'selected':'' ?>><?= $x ?></option><?php endforeach;?></select></div><div class="form-group"><label>Tensão da rede</label><select name="tensao_rede"><?php foreach(['127/220','220/380','220','380'] as $x):?><option <?= ($v['tensao_rede']??'127/220')===$x?'selected':'' ?>><?= $x ?> V</option><?php endforeach;?></select></div><div class="form-group"><label><input type="checkbox" name="inclui_iluminacao" value="1" <?= !empty($v['inclui_iluminacao'])?'checked':'' ?>> Incluir iluminação pública</label></div><div class="form-group"><label>Valor da iluminação (R$)</label><input type="number" step="0.01" name="valor_iluminacao" value="<?= htmlspecialchars($v['valor_iluminacao']??0) ?>"></div></div></div></div></div>
<div class="wizard-pane" data-step="3"><div class="card"><div class="card-header"><span class="card-title">Irradiação solar para cálculo</span></div><div class="card-body"><div class="form-row cols-4"><div class="form-group"><label>Estado</label><input id="estado" name="estado" value="<?= htmlspecialchars($v['estado']??'') ?>"></div><div class="form-group"><label>Cidade</label><input id="cidade" name="cidade" value="<?= htmlspecialchars($v['cidade']??'') ?>"></div><div class="form-group"><label>HSP médio (kWh/m²/dia)</label><input id="hsp" type="number" step="0.01" name="hsp" value="<?= htmlspecialchars($v['hsp']??'5.25') ?>"></div><div class="form-group"><label>Localidade da usina</label><input id="localidade" name="localidade" value="<?= htmlspecialchars($v['localidade']??'') ?>"></div></div><div class="solar-results"><div><small>HSP INFORMADO</small><strong id="hspResultado">5,25 kWh/m²</strong></div><div><small>POTÊNCIA ESTIMADA</small><strong id="potenciaResultado">0,00 kWp</strong></div></div><p class="form-hint">O HSP pode ser ajustado conforme a base solarimétrica usada pela empresa. O mapa é opcional e pode ser consultado pelo endereço.</p><a id="mapLink" class="btn btn-outline" href="#" target="_blank" rel="noopener"><i class="fa-solid fa-location-dot"></i> Abrir localidade no mapa</a></div></div></div>
<div class="wizard-pane" data-step="4"><div class="card"><div class="card-header"><span class="card-title">Dimensionamento e equipamentos</span><button type="button" class="btn btn-primary btn-sm" onclick="dimensionar()"><i class="fa-solid fa-gears"></i> Dimensionar</button></div><div class="card-body"><div class="form-row cols-4"><div class="form-group"><label>Fornecedor</label><input name="fornecedor_nome" value="<?= htmlspecialchars($v['fornecedor_nome']??'MF Solar') ?>"></div><div class="form-group"><label>Tipo de dimensionamento</label><select name="tipo_dimensionamento"><option>Por equipamento</option><option>Por potência</option></select></div><div class="form-group"><label>Painel / modelo</label><input name="painel_descricao" value="<?= htmlspecialchars($v['painel_descricao']??'') ?>"></div><div class="form-group"><label>Potência do painel (Wp)</label><input id="painelWp" type="number" step="1" name="painel_potencia_wp" value="<?= htmlspecialchars($v['painel_potencia_wp']??'550') ?>"></div></div><div class="form-row cols-4"><div class="form-group"><label>Inversor</label><input name="inversor_descricao" value="<?= htmlspecialchars($v['inversor_descricao']??'') ?>"></div><div class="form-group"><label>Estrutura</label><input id="estrutura" name="tipo_estrutura" value="<?= htmlspecialchars($v['tipo_estrutura']??'Telha Fibrocimento') ?>"></div><div class="form-group"><label>Potência (kWp)</label><input id="potenciaKwp" type="number" step="0.01" name="potencia_kwp" value="<?= htmlspecialchars($v['potencia_kwp']??'') ?>"></div><div class="form-group"><label>Quantidade de módulos</label><input id="qtdModulos" type="number" name="quantidade_modulos" value="<?= htmlspecialchars($v['quantidade_modulos']??'') ?>"></div></div><div class="form-row cols-3"><div class="form-group"><label>Área necessária (m²)</label><input id="areaM2" type="number" step="0.01" name="area_necessaria_m2" value="<?= htmlspecialchars($v['area_necessaria_m2']??'') ?>"></div><div class="form-group"><label>Geração anual (kWh)</label><input id="geracaoAnual" type="number" step="0.01" name="geracao_anual_kwh" value="<?= htmlspecialchars($v['geracao_anual_kwh']??'') ?>"></div><div class="form-group"><label>Geração média mensal (kWh)</label><input id="geracaoMensal" type="number" step="0.01" name="geracao_mensal_kwh" value="<?= htmlspecialchars($v['geracao_mensal_kwh']??'') ?>"></div></div></div></div>
</div><div class="wizard-pane" data-step="5"><div class="card"><div class="card-header"><span class="card-title">Geração e consumo mês a mês</span><button type="button" class="btn btn-outline btn-sm" onclick="preencherMeses()"><i class="fa-solid fa-wand-magic-sparkles"></i> Distribuir médias</button></div><div class="card-body"><div class="month-grid"><?php foreach($meses as $i=>$m):?><div class="month-box"><strong><?= strtoupper($m) ?></strong><label>Geração</label><input type="number" step="0.01" name="geracao_<?= $m ?>" value="<?= htmlspecialchars($ger[$i]??'') ?>"><label>Consumo</label><input type="number" step="0.01" name="consumo_<?= $m ?>" value="<?= htmlspecialchars($con[$i]??'') ?>"></div><?php endforeach;?></div></div></div>
<div class="card"><div class="card-header"><span class="card-title">Equipamentos e serviços</span><button type="button" class="btn btn-outline btn-sm" onclick="addItem()"><i class="fa-solid fa-plus"></i> Adicionar item</button></div><div class="card-body"><div class="table-wrap"><table id="itens"><thead><tr><th>Produto</th><th>Descrição</th><th>Qtd.</th><th>Un.</th><th>Preço</th><th>Total</th><th></th></tr></thead><tbody><?php foreach($itens as $it):?><tr><td><select name="item_produto[]" onchange="produtoSelecionado(this)"><option value="">Livre</option><?php foreach($produtos as $pr):?><option value="<?= $pr['id'] ?>" data-nome="<?= htmlspecialchars($pr['nome']) ?>" data-unidade="<?= htmlspecialchars($pr['unidade']) ?>" data-preco="<?= (float)$pr['preco_venda'] ?>" <?= ($it['produto_id']??'')==$pr['id']?'selected':'' ?>><?= htmlspecialchars($pr['codigo'].' '.$pr['nome']) ?></option><?php endforeach;?></select></td><td><input name="item_descricao[]" value="<?= htmlspecialchars($it['descricao']??'') ?>" required></td><td><input class="item-qtd" type="number" step="0.01" name="item_quantidade[]" value="<?= htmlspecialchars($it['quantidade']??1) ?>" oninput="calcular()"></td><td><input class="item-un" name="item_unidade[]" value="<?= htmlspecialchars($it['unidade']??'un') ?>"></td><td><input class="item-preco" type="number" step="0.01" name="item_preco[]" value="<?= htmlspecialchars($it['preco_unitario']??0) ?>" oninput="calcular()"></td><td class="item-total">R$ 0,00</td><td><button type="button" class="btn btn-danger btn-sm btn-icon" onclick="this.closest('tr').remove();calcular()"><i class="fa-solid fa-trash"></i></button></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="card"><div class="card-header"><span class="card-title">Valores e condições</span></div><div class="card-body"><div class="form-row cols-4"><div class="form-group"><label>Equipamentos</label><input id="equipamentos" type="number" step="0.01" name="valor_equipamentos" value="<?= htmlspecialchars($v['valor_equipamentos']??0) ?>" oninput="calcularResumo()"></div><div class="form-group"><label>Serviços</label><input id="servicos" type="number" step="0.01" name="valor_servicos" value="<?= htmlspecialchars($v['valor_servicos']??0) ?>" oninput="calcularResumo()"></div><div class="form-group"><label>Desconto</label><input id="desconto" type="number" step="0.01" name="desconto" value="<?= htmlspecialchars($v['desconto']??0) ?>" oninput="calcularResumo()"></div><div class="form-group"><label>Valor total</label><input id="valorTotal" type="number" step="0.01" name="valor_total" value="<?= htmlspecialchars($v['valor_total']??0) ?>" readonly></div></div><div class="form-row cols-3"><div class="form-group"><label>Entrada</label><input id="entrada" type="number" step="0.01" name="entrada" value="<?= htmlspecialchars($v['entrada']??0) ?>" oninput="calcularResumo()"></div><div class="form-group"><label>Saldo</label><input id="saldo" type="number" step="0.01" name="saldo" value="<?= htmlspecialchars($v['saldo']??0) ?>" readonly></div><div class="form-group"><label>Condições de pagamento</label><input name="condicoes_pagamento" value="<?= htmlspecialchars($v['condicoes_pagamento']??'Entrada + saldo a definir') ?>"></div></div><div class="form-row cols-2"><div class="form-group"><label>Incluso na proposta</label><textarea name="itens_inclusos" rows="5"><?= htmlspecialchars($v['itens_inclusos']??'Instalação do sistema; projeto solar fotovoltaico; material elétrico; ART de projeto e execução; acompanhamento junto à distribuidora; monitoramento via web.') ?></textarea></div><div class="form-group"><label>Observações</label><textarea name="observacoes" rows="5"><?= htmlspecialchars($v['observacoes']??'A instalação deve ser executada por equipe qualificada e conforme as normas técnicas aplicáveis.') ?></textarea></div></div></div></div>
</div><div class="wizard-actions"><button type="button" id="btnAnterior" class="btn btn-outline">Voltar</button><button type="button" id="btnProximo" class="btn btn-primary">Avançar</button><a href="index.php" class="btn btn-outline">Cancelar</a><button id="btnSalvar" class="btn btn-primary" style="display:none"><i class="fa-solid fa-floppy-disk"></i> Salvar e gerar proposta</button></div></form>
<template id="itemTpl"><tr><td><select name="item_produto[]" onchange="produtoSelecionado(this)"><option value="">Livre</option><?php foreach($produtos as $pr):?><option value="<?= $pr['id'] ?>" data-nome="<?= htmlspecialchars($pr['nome']) ?>" data-unidade="<?= htmlspecialchars($pr['unidade']) ?>" data-preco="<?= (float)$pr['preco_venda'] ?>"><?= htmlspecialchars($pr['codigo'].' '.$pr['nome']) ?></option><?php endforeach;?></select></td><td><input name="item_descricao[]" required></td><td><input class="item-qtd" type="number" step="0.01" name="item_quantidade[]" value="1" oninput="calcular()"></td><td><input class="item-un" name="item_unidade[]" value="un"></td><td><input class="item-preco" type="number" step="0.01" name="item_preco[]" value="0" oninput="calcular()"></td><td class="item-total">R$ 0,00</td><td><button type="button" class="btn btn-danger btn-sm btn-icon" onclick="this.closest('tr').remove();calcular()"><i class="fa-solid fa-trash"></i></button></td></tr></template>
<script>
const money=v=>'R$ '+Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
function addItem(){document.querySelector('#itens tbody').append(document.getElementById('itemTpl').content.cloneNode(true));}
function produtoSelecionado(s){const o=s.selectedOptions[0],tr=s.closest('tr');if(!o.value)return;tr.querySelector('[name="item_descricao[]"]').value=o.dataset.nome;tr.querySelector('.item-un').value=o.dataset.unidade;tr.querySelector('.item-preco').value=o.dataset.preco;calcular();}
function calcular(){let soma=0;document.querySelectorAll('#itens tbody tr').forEach(tr=>{let t=(parseFloat(tr.querySelector('.item-qtd').value)||0)*(parseFloat(tr.querySelector('.item-preco').value)||0);tr.querySelector('.item-total').textContent=money(t);soma+=t;});document.getElementById('equipamentos').value=soma.toFixed(2);calcularResumo();}
function calcularResumo(){const equipamentos=document.getElementById('equipamentos'),servicos=document.getElementById('servicos'),desconto=document.getElementById('desconto'),valorTotal=document.getElementById('valorTotal'),entrada=document.getElementById('entrada'),saldo=document.getElementById('saldo');let total=(parseFloat(equipamentos.value)||0)+(parseFloat(servicos.value)||0)-(parseFloat(desconto.value)||0);valorTotal.value=Math.max(0,total).toFixed(2);saldo.value=Math.max(0,total-(parseFloat(entrada.value)||0)).toFixed(2);}
function preencherMeses(){let g=parseFloat(document.getElementById('geracaoMensal').value)||0,c=parseFloat(document.getElementById('consumoMensal').value)||0;document.querySelectorAll('[name^="geracao_"]').forEach(i=>{if(!['geracao_anual_kwh','geracao_mensal_kwh'].includes(i.name))i.value=g.toFixed(2)});document.querySelectorAll('[name^="consumo_"]').forEach(i=>i.value=c.toFixed(2));}
function atualizarEstimativa(){const c=parseFloat(document.getElementById('consumoMensal').value)||0,h=parseFloat(document.getElementById('hsp').value)||0,e=(parseFloat(document.getElementById('eficiencia').value)||80)/100;const p=h&&e?c/(h*30*e):0;document.getElementById('hspResultado').textContent=h.toLocaleString('pt-BR',{minimumFractionDigits:2})+' kWh/m²';document.getElementById('potenciaResultado').textContent=p.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+' kWp';const q=[document.getElementById('cidade').value,document.getElementById('estado').value].filter(Boolean).join(', ');document.getElementById('mapLink').href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q||document.getElementById('localidade').value);return p;}
function dimensionar(){const p=atualizarEstimativa(),wp=parseFloat(document.getElementById('painelWp').value)||550,kwp=Math.ceil((p*1000)/wp)*wp/1000,q=Math.max(1,Math.ceil((p*1000)/wp)),h=parseFloat(document.getElementById('hsp').value)||0,e=(parseFloat(document.getElementById('eficiencia').value)||80)/100,g=kwp*h*30*e;document.getElementById('potenciaKwp').value=kwp.toFixed(2);document.getElementById('qtdModulos').value=q;document.getElementById('areaM2').value=(q*2.2).toFixed(2);document.getElementById('geracaoMensal').value=g.toFixed(2);document.getElementById('geracaoAnual').value=(g*12).toFixed(2);}
document.getElementById('cliente').addEventListener('change',function(){const o=this.selectedOptions[0],localidade=document.getElementById('localidade'),estrutura=document.getElementById('estrutura');if(!localidade.value)localidade.value=o.dataset.local||'';if(!estrutura.value)estrutura.value=(o.dataset.estrutura||'').replace('_',' ');document.getElementById('cidade').value=o.dataset.cidade||'';document.getElementById('estado').value=o.dataset.estado||'';if(!document.getElementById('consumoMensal').value)document.getElementById('consumoMensal').value=o.dataset.consumo||'';document.getElementById('clienteResumo').textContent=o.value?`${o.dataset.nome} • ${o.dataset.local||'Local não informado'} • Consumo cadastrado: ${o.dataset.consumo||0} kWh/mês`:'Selecione um cliente.';atualizarEstimativa();});
['consumoMensal','hsp','eficiencia','cidade','estado'].forEach(id=>document.getElementById(id).addEventListener('input',atualizarEstimativa));
let passo=1;function mostrarPasso(n){passo=Math.max(1,Math.min(5,n));document.querySelectorAll('.wizard-pane').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===passo));document.querySelectorAll('.proposal-steps button').forEach(x=>x.classList.toggle('active',Number(x.dataset.go)===passo));document.getElementById('btnAnterior').style.visibility=passo===1?'hidden':'visible';document.getElementById('btnProximo').style.display=passo===5?'none':'inline-flex';document.getElementById('btnSalvar').style.display=passo===5?'inline-flex':'none';window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('.proposal-steps button').forEach(b=>b.addEventListener('click',()=>mostrarPasso(Number(b.dataset.go))));document.getElementById('btnAnterior').addEventListener('click',()=>mostrarPasso(passo-1));document.getElementById('btnProximo').addEventListener('click',()=>mostrarPasso(passo+1));
calcular();atualizarEstimativa();mostrarPasso(1);if(document.getElementById('cliente').value)document.getElementById('cliente').dispatchEvent(new Event('change'));
</script>
<?php require_once __DIR__ . '/../../includes/footer.php'; ?>
