<?php
require_once __DIR__ . '/../../includes/auth.php';requireLogin();$db=getDB();$id=(int)($_GET['id']??0);
$st=$db->prepare("SELECT p.*,COALESCE(c.nome,c.nome_fantasia,c.razao_social) cliente,c.cpf,c.cnpj FROM propostas p JOIN clientes c ON c.id=p.cliente_id WHERE p.id=?");$st->execute([$id]);$p=$st->fetch();if(!$p)die('Proposta não encontrada.');
$st=$db->prepare('SELECT * FROM proposta_itens WHERE proposta_id=? ORDER BY ordem,id');$st->execute([$id]);$itens=$st->fetchAll();
$ger=json_decode($p['geracao_meses']??'[]',true)?:array_fill(0,12,0);$con=json_decode($p['consumo_meses']??'[]',true)?:array_fill(0,12,0);$meses=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
function brmoney($v){return number_format((float)$v,2,',','.');}function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}$bg=BASE_URL.'/assets/img/propostas/modelo-oficial/pagina-';
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($p['numero']) ?> - <?= e($p['cliente']) ?></title><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><style>
*{box-sizing:border-box}body{margin:0;background:#d9dde5;color:#111;font-family:Arial,sans-serif}.actions{position:fixed;z-index:50;right:18px;top:18px;display:flex;gap:8px}.actions button,.actions a{border:0;border-radius:7px;padding:10px 15px;background:#142a78;color:#fff;text-decoration:none;font-weight:bold;cursor:pointer}.pdf-page{position:relative;width:210mm;height:297mm;margin:10px auto;background:#fff;overflow:hidden;page-break-after:always;box-shadow:0 3px 18px #0003}.pdf-page:last-of-type{page-break-after:auto}.page-bg{position:absolute;inset:0;width:100%;height:100%;object-fit:fill}.overlay{position:absolute;background:#fff}.cover-data{left:69mm;top:268mm;width:76mm;height:16mm;background:#272d65;color:#fff;text-align:center;padding-top:2mm;font-size:10px;font-weight:700;line-height:1.5}.p5{left:13mm;top:44mm;width:184mm;height:239mm;padding:0 4mm}.p5 h1,.p6 h1{font-size:10px;text-align:center;margin:0 0 4mm}.p5 h2{font-size:9px;margin:4mm 0 3mm}.details{width:100%;border-collapse:collapse;font-size:7.4px}.details td,.details th{height:5.4mm;padding:0 1mm}.details td{width:72%}.details th{text-align:left}.chart-title{text-align:center;font-size:9px;font-weight:700;margin:5mm 0 0}.chart-sub{text-align:center;font-size:7px;font-weight:700;margin:1mm 0 2mm}.chart-box{height:76mm;width:100%;padding:0 8mm}.months{width:100%;border-collapse:collapse;font-size:5.3px;text-align:center;margin-top:1mm}.months th,.months td{padding:1.2mm .4mm;border:1px solid #eee}.months th:first-child{background:#075493;color:#fff}.months tr:last-child th:first-child{background:#f5c400;color:#111}.p6{left:13mm;top:47mm;width:184mm;height:219mm}.equipment-spacer{height:91mm}.items{width:100%;border-collapse:collapse;font-size:7px}.items th,.items td{border:1px solid #999;padding:1.2mm}.items th{font-weight:700}.items .qty{width:18mm;text-align:center}.total{background:#172a76;color:#fff;text-align:center;font-size:12px;font-weight:bold;padding:2.6mm}.included{text-align:center;font-size:5.6px;line-height:1.4;margin:6mm}.p7{left:13mm;top:46mm;width:184mm;height:227mm;padding:0 4mm;font-size:8px}.p7 h2{font-size:8px;margin:0 0 3mm}.p7 .obs{font-weight:600;line-height:1.45;min-height:45mm}.dates{line-height:1.8}.signatures{position:absolute;left:4mm;right:4mm;top:111mm;display:grid;grid-template-columns:1fr 1fr;gap:16mm;text-align:center;font-size:6.5px}.signatures div{border-top:1px solid #111;padding-top:2mm}@media print{body{background:#fff}.actions{display:none}.pdf-page{margin:0;box-shadow:none}@page{size:A4;margin:0}}
</style></head><body><div class="actions"><button onclick="window.print()">Imprimir / Salvar PDF</button><a href="view.php?id=<?= $id ?>">Voltar</a></div>
<section class="pdf-page"><img class="page-bg" src="<?= $bg ?>1.png"><div class="cover-data"><?= e(mb_strtoupper($p['cliente'])) ?><br>PROPOSTA # <?= e($p['numero']) ?></div></section>
<section class="pdf-page"><img class="page-bg" src="<?= $bg ?>2.png"></section><section class="pdf-page"><img class="page-bg" src="<?= $bg ?>3.png"></section><section class="pdf-page"><img class="page-bg" src="<?= $bg ?>4.png"></section>
<section class="pdf-page"><img class="page-bg" src="<?= $bg ?>5.png"><div class="overlay p5"><h1>DETALHES DA PROPOSTA<br><br><?= e($p['titulo']) ?></h1><h2>DIMENSIONAMENTO</h2><table class="details"><tr><td>Localidade da usina</td><th><?= e($p['localidade']) ?></th></tr><tr><td>Tipo de estrutura</td><th><?= e($p['tipo_estrutura']) ?></th></tr><tr><td>Potência do sistema dimensionado</td><th><?= brmoney($p['potencia_kwp']) ?> kWp</th></tr><tr><td>Quantidade de módulos dimensionados</td><th><?= (int)$p['quantidade_modulos'] ?></th></tr><tr><td>Energia estimada a ser gerada pela potência dimensionada (média anual)</td><th><?= brmoney($p['geracao_anual_kwh']) ?> kWh</th></tr><tr><td>Área útil necessária para a instalação (estimada)</td><th><?= brmoney($p['area_necessaria_m2']) ?> m²</th></tr><tr><td>Energia estimada a ser gerada pela potência dimensionada (média mensal)</td><th><?= brmoney($p['geracao_mensal_kwh']) ?> kWh</th></tr></table><div class="chart-title">GERAÇÃO DE ENERGIA</div><div class="chart-sub">Estimativa de geração mês a mês</div><div class="chart-box"><canvas id="geracaoChart"></canvas></div><table class="months"><tr><th></th><?php foreach($meses as $m):?><th><?= $m ?></th><?php endforeach;?></tr><tr><th>GERAÇÃO</th><?php foreach($ger as $x):?><td><?= number_format((float)$x,2,',','.') ?></td><?php endforeach;?></tr><tr><th>CONSUMO</th><?php foreach($con as $x):?><td><?= number_format((float)$x,2,',','.') ?></td><?php endforeach;?></tr></table></div></section>
<section class="pdf-page"><img class="page-bg" src="<?= $bg ?>6.png"><div class="overlay p6"><h1>EQUIPAMENTOS</h1><div class="equipment-spacer"></div><table class="items"><thead><tr><th>ITEM / DESCRIÇÃO</th><th class="qty">QUANT</th></tr></thead><tbody><?php foreach($itens as $i):?><tr><td><?= e($i['descricao']) ?></td><td class="qty"><?= brmoney($i['quantidade']) ?></td></tr><?php endforeach;?></tbody></table><div class="total">VALOR TOTAL: <?= brmoney($p['valor_total']) ?></div><div class="included">Também estão inclusos neste orçamento: <?= e(str_replace(';',',',$p['itens_inclusos'])) ?></div></div></section>
<section class="pdf-page"><img class="page-bg" src="<?= $bg ?>7.png"><div class="overlay p7"><h2>OBSERVAÇÕES:</h2><div class="obs"><?= nl2br(e($p['observacoes'])) ?></div><div class="dates">Proposta válida até <?= $p['validade']?date('d/m/Y',strtotime($p['validade'])):'data a definir' ?>.<br><br><?= date('d/m/Y',strtotime($p['data_proposta'])) ?>.</div><div class="signatures"><div>MF ENERGIA SOLAR E INSTALAÇÕES ELÉTRICAS<br>CNPJ: 34.877.815/0001-75</div><div>Cliente: <?= e(mb_strtoupper($p['cliente'])) ?><br><?= $p['cpf']?'CPF: '.e($p['cpf']):'CNPJ: '.e($p['cnpj']) ?></div></div></div></section>
<script>new Chart(document.getElementById('geracaoChart'),{type:'bar',data:{labels:<?= json_encode($meses) ?>,datasets:[{label:'Ger. Mensal',data:<?= json_encode(array_values($ger)) ?>,backgroundColor:'#142a78'},{label:'Consumo',data:<?= json_encode(array_values($con)) ?>,backgroundColor:'#f5c400'}]},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{position:'top',labels:{boxWidth:28,font:{size:8}}}},scales:{x:{ticks:{font:{size:7}}},y:{ticks:{font:{size:7}},beginAtZero:true}}}});</script></body></html>
