<?php
require_once __DIR__ . '/../../includes/header.php';$db=getDB();$id=(int)($_GET['id']??0);
$st=$db->prepare("SELECT p.*,COALESCE(c.nome,c.nome_fantasia,c.razao_social) cliente,c.cpf,c.cnpj,u.nome vendedor FROM propostas p JOIN clientes c ON c.id=p.cliente_id LEFT JOIN usuarios u ON u.id=p.usuario_id WHERE p.id=?");$st->execute([$id]);$p=$st->fetch();if(!$p){header('Location:index.php');exit;}
$st=$db->prepare('SELECT * FROM proposta_itens WHERE proposta_id=? ORDER BY ordem,id');$st->execute([$id]);$itens=$st->fetchAll();$labels=['rascunho'=>'Rascunho','enviada'=>'Enviada','aprovada'=>'Aprovada','recusada'=>'Recusada','vencida'=>'Vencida','convertida'=>'Convertida em OS'];
?>
<div class="page-header"><div class="page-title"><i class="fa-solid fa-file-signature"></i> <?= htmlspecialchars($p['numero']) ?> <small><?= htmlspecialchars($p['cliente']) ?></small></div><div style="display:flex;gap:8px;flex-wrap:wrap"><a href="index.php" class="btn btn-outline"><i class="fa-solid fa-arrow-left"></i> Voltar</a><a href="form.php?id=<?= $id ?>" class="btn btn-outline"><i class="fa-solid fa-pen"></i> Editar</a><a href="imprimir.php?id=<?= $id ?>" target="_blank" class="btn btn-primary"><i class="fa-solid fa-file-pdf"></i> Imprimir/PDF</a><?php if($p['status']==='aprovada'&&!$p['ordem_servico_id']):?><a href="converter_os.php?id=<?= $id ?>" class="btn btn-success" onclick="return confirm('Converter esta proposta aprovada em Ordem de Serviço?')"><i class="fa-solid fa-arrow-right-arrow-left"></i> Converter em OS</a><?php endif;?></div></div>
<?php if(!empty($_SESSION['msg'])):?><div class="alert alert-success"><?= htmlspecialchars($_SESSION['msg']);unset($_SESSION['msg']); ?></div><?php endif;?>
<div class="grid-2"><div class="card"><div class="card-header"><span class="card-title">Dados comerciais</span><span class="badge badge-primary"><?= $labels[$p['status']]??$p['status'] ?></span></div><div class="card-body"><p><strong>Cliente:</strong> <?= htmlspecialchars($p['cliente']) ?></p><p><strong>Data:</strong> <?= date('d/m/Y',strtotime($p['data_proposta'])) ?></p><p><strong>Validade:</strong> <?= $p['validade']?date('d/m/Y',strtotime($p['validade'])):'–' ?></p><p><strong>Vendedor:</strong> <?= htmlspecialchars($p['vendedor']??'–') ?></p><p><strong>Pagamento:</strong> <?= htmlspecialchars($p['condicoes_pagamento']??'–') ?></p></div></div><div class="card"><div class="card-header"><span class="card-title">Dimensionamento</span></div><div class="card-body"><p><strong>Local:</strong> <?= htmlspecialchars($p['localidade']??'–') ?></p><p><strong>Estrutura:</strong> <?= htmlspecialchars($p['tipo_estrutura']??'–') ?></p><p><strong>Potência:</strong> <?= number_format((float)$p['potencia_kwp'],2,',','.') ?> kWp</p><p><strong>Módulos:</strong> <?= (int)$p['quantidade_modulos'] ?></p><p><strong>Geração média:</strong> <?= number_format((float)$p['geracao_mensal_kwh'],2,',','.') ?> kWh/mês</p></div></div></div>
<div class="card"><div class="card-header"><span class="card-title">Itens</span></div><div class="table-wrap"><table><thead><tr><th>Descrição</th><th>Qtd.</th><th>Un.</th><th>Preço</th><th>Total</th></tr></thead><tbody><?php foreach($itens as $i):?><tr><td><?= htmlspecialchars($i['descricao']) ?></td><td><?= number_format((float)$i['quantidade'],2,',','.') ?></td><td><?= htmlspecialchars($i['unidade']) ?></td><td>R$ <?= number_format((float)$i['preco_unitario'],2,',','.') ?></td><td>R$ <?= number_format((float)$i['total'],2,',','.') ?></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="grid-3"><div class="kpi-card"><div><div class="kpi-label">VALOR TOTAL</div><div class="kpi-value">R$ <?= number_format((float)$p['valor_total'],2,',','.') ?></div></div></div><div class="kpi-card green"><div><div class="kpi-label">ENTRADA</div><div class="kpi-value">R$ <?= number_format((float)$p['entrada'],2,',','.') ?></div></div></div><div class="kpi-card yellow"><div><div class="kpi-label">SALDO</div><div class="kpi-value">R$ <?= number_format((float)$p['saldo'],2,',','.') ?></div></div></div></div>
<?php require_once __DIR__ . '/../../includes/footer.php'; ?>
