<?php
require_once __DIR__ . '/../../includes/auth.php';requireLogin();if(!hasRole('admin','gerente','financeiro')){http_response_code(403);die('Acesso restrito ao financeiro.');}require_once __DIR__ . '/../../includes/header.php';
$db=getDB();
if(empty($_SESSION['csrf_financeiro']))$_SESSION['csrf_financeiro']=bin2hex(random_bytes(24));
$tipo=$_GET['tipo']??'';$status=$_GET['status']??'';$de=$_GET['de']??date('Y-m-01');$ate=$_GET['ate']??date('Y-m-t');
$where=['COALESCE(c.data_vencimento,DATE(c.created_at)) BETWEEN ? AND ?'];$params=[$de,$ate];
if(in_array($tipo,['receber','pagar'],true)){$where[]='c.tipo=?';$params[]=$tipo;}
if(in_array($status,['pendente','pago','atrasado','cancelado'],true)){$where[]="(CASE WHEN c.status='pendente' AND c.data_vencimento<CURDATE() THEN 'atrasado' ELSE c.status END)=?";$params[]=$status;}
$sql="SELECT c.*,COALESCE(cl.nome,cl.nome_fantasia,cl.razao_social) cliente,os.numero os_numero,(CASE WHEN c.status='pendente' AND c.data_vencimento<CURDATE() THEN 'atrasado' ELSE c.status END) status_exibicao FROM contas c LEFT JOIN clientes cl ON cl.id=c.cliente_id LEFT JOIN ordens_servico os ON os.id=c.ordem_servico_id WHERE ".implode(' AND ',$where).' ORDER BY c.data_vencimento,c.id DESC';
$st=$db->prepare($sql);$st->execute($params);$contas=$st->fetchAll();
$resumo=$db->query("SELECT IFNULL(SUM(CASE WHEN tipo='receber' AND status='pago' AND data_pagamento BETWEEN DATE_FORMAT(CURDATE(),'%Y-%m-01') AND LAST_DAY(CURDATE()) THEN valor ELSE 0 END),0) recebido,IFNULL(SUM(CASE WHEN tipo='pagar' AND status='pago' AND data_pagamento BETWEEN DATE_FORMAT(CURDATE(),'%Y-%m-01') AND LAST_DAY(CURDATE()) THEN valor ELSE 0 END),0) pago,IFNULL(SUM(CASE WHEN tipo='receber' AND status='pendente' THEN valor ELSE 0 END),0) receber,IFNULL(SUM(CASE WHEN tipo='pagar' AND status='pendente' THEN valor ELSE 0 END),0) pagar FROM contas")->fetch();
$labels=['pendente'=>'Pendente','pago'=>'Pago','atrasado'=>'Atrasado','cancelado'=>'Cancelado'];$badges=['pendente'=>'warning','pago'=>'success','atrasado'=>'danger','cancelado'=>'gray'];
?>
<div class="page-header"><div class="page-title"><i class="fa-solid fa-dollar-sign"></i> Financeiro</div><a class="btn btn-primary" href="form.php"><i class="fa-solid fa-plus"></i> Novo lançamento</a></div>
<?php if(!empty($_SESSION['msg'])):?><div class="alert alert-success"><?= htmlspecialchars($_SESSION['msg']);unset($_SESSION['msg']);?></div><?php endif;?>
<div class="grid-4"><div class="kpi-card green"><div><div class="kpi-label">RECEBIDO NO MÊS</div><div class="kpi-value">R$ <?= number_format($resumo['recebido'],2,',','.') ?></div></div></div><div class="kpi-card yellow"><div><div class="kpi-label">A RECEBER</div><div class="kpi-value">R$ <?= number_format($resumo['receber'],2,',','.') ?></div></div></div><div class="kpi-card"><div><div class="kpi-label">PAGO NO MÊS</div><div class="kpi-value">R$ <?= number_format($resumo['pago'],2,',','.') ?></div></div></div><div class="kpi-card cyan"><div><div class="kpi-label">SALDO DO MÊS</div><div class="kpi-value">R$ <?= number_format($resumo['recebido']-$resumo['pago'],2,',','.') ?></div></div></div></div>
<div class="card"><div class="card-body"><form method="GET" class="form-row cols-4"><div class="form-group"><label>Tipo</label><select name="tipo"><option value="">Todos</option><option value="receber" <?= $tipo==='receber'?'selected':'' ?>>A receber</option><option value="pagar" <?= $tipo==='pagar'?'selected':'' ?>>A pagar</option></select></div><div class="form-group"><label>Situação</label><select name="status"><option value="">Todas</option><?php foreach($labels as $k=>$l):?><option value="<?= $k ?>" <?= $status===$k?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></div><div class="form-group"><label>Vencimento de</label><input type="date" name="de" value="<?= htmlspecialchars($de) ?>"></div><div class="form-group"><label>Até</label><input type="date" name="ate" value="<?= htmlspecialchars($ate) ?>"></div><div><button class="btn btn-primary"><i class="fa-solid fa-filter"></i> Filtrar</button></div></form></div></div>
<div class="card"><div class="card-header"><span class="card-title">Lançamentos</span><span><?= count($contas) ?> registro(s)</span></div><div class="table-wrap"><table><thead><tr><th>Vencimento</th><th>Tipo</th><th>Descrição</th><th>Cliente/OS</th><th>Parcela</th><th>Valor</th><th>Situação</th><th>Ações</th></tr></thead><tbody><?php foreach($contas as $c):?><tr><td><?= $c['data_vencimento']?date('d/m/Y',strtotime($c['data_vencimento'])):'–' ?></td><td><span class="badge <?= $c['tipo']==='receber'?'badge-success':'badge-danger' ?>"><?= $c['tipo']==='receber'?'Receber':'Pagar' ?></span></td><td><?= htmlspecialchars($c['descricao']) ?></td><td><?= htmlspecialchars($c['cliente']??'–') ?><?= $c['os_numero']?' / '.htmlspecialchars($c['os_numero']):'' ?></td><td><?= (int)$c['parcela_atual'].'/'.(int)$c['total_parcelas'] ?></td><td><strong>R$ <?= number_format($c['valor'],2,',','.') ?></strong></td><td><span class="badge badge-<?= $badges[$c['status_exibicao']]??'gray' ?>"><?= $labels[$c['status_exibicao']]??$c['status_exibicao'] ?></span></td><td style="white-space:nowrap"><a class="btn btn-outline btn-sm btn-icon" href="form.php?id=<?= $c['id'] ?>" title="Editar"><i class="fa-solid fa-pen"></i></a><?php if($c['status_exibicao']!=='pago'&&$c['status_exibicao']!=='cancelado'):?><form method="POST" action="acao.php" style="display:inline"><input type="hidden" name="csrf" value="<?= $_SESSION['csrf_financeiro'] ?>"><input type="hidden" name="id" value="<?= $c['id'] ?>"><input type="hidden" name="acao" value="pagar"><button class="btn btn-success btn-sm btn-icon" title="Marcar como pago"><i class="fa-solid fa-check"></i></button></form><?php endif;?><form method="POST" action="acao.php" style="display:inline" onsubmit="return confirm('Cancelar este lançamento?')"><input type="hidden" name="csrf" value="<?= $_SESSION['csrf_financeiro'] ?>"><input type="hidden" name="id" value="<?= $c['id'] ?>"><input type="hidden" name="acao" value="cancelar"><button class="btn btn-danger btn-sm btn-icon" title="Cancelar"><i class="fa-solid fa-ban"></i></button></form></td></tr><?php endforeach;?><?php if(!$contas):?><tr><td colspan="8" style="text-align:center;padding:35px">Nenhum lançamento encontrado.</td></tr><?php endif;?></tbody></table></div></div>
<?php require_once __DIR__ . '/../../includes/footer.php'; ?>
